site_name: URSSI Documentation updated
site_url: https://ben-lew.github.io/urssi-docs/
theme:
  name: material

nav:
  - Overview: index.md
  - Docs Deployment: docs_setup.md
  - Repository Documentation: repo_setup.md
  - GitHub Repo Settings: gh_repo_settings.md
  - Documenting Code: docstrings.md
  - Making Your Docs Shine: advanced_markdown.md
  - Notebooks: notebooks.ipynb
  - Versioning: versioning.md


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - mkdocs-jupyter:

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
